# Config file for settings affecting the whole blog. For technical reasons
# this file is *NOT* auto-reloaded with 'bundle exec jekyll serve'; after
# making changes here restart the server for them to take effect.

# Site settings
# These are used to personalize your new site. If you look in the HTML
# files, you will see them accessed via {{ site.title }}, {{ site.email }},
# and so on. You can create any custom variable you would like, and they
# will be accessible in the templates via {{ site.myvariable }}.
title: Wren
author:
  name: Renny Wrennington
  email: email@email.com
description: >-  # this means to ignore newlines until the next key
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/Wren"  # the subpath of your site, e.g. /blog, or "/" for root

# Build settings
markdown: kramdown  # enables extended markdown features (e.g footnotes)
remote_theme: foggalong/wren@v0.3-beta  # fetch Wren from GitHub
# theme: jekyll-wren  # use Wren from Ruby Gem

# External plugins to bring in
plugins:
  - jekyll-remote-theme  # fetching themes from GitHub
  - jekyll-paginate      # pagination
  - jekyll-feed          # rss feeds (default Jekyll)
  - jekyll-seo-tag       # search engine optimization (default Minima)

# These items will not be processed or trigger regeneration by default.
# Any item listed under the `exclude:` key here will be automatically
# added to the internal "default list". Excluded items can be processed
# by explicitly listing the directories or their entries' file path in
# the `include:` list.
exclude:
  - _drafts
  - .jekyll-cache/
  - .sass-cache/
  - .editorconfig
  - .github/
  - .gitignore
  - build
  - Gemfile
  - Gemfile.lock
  - jekyll-wren.gemspec
  - LICENSE.md
  - README.md

# Splits blog feed into pages; comment these two lines and the
# Paginate navigation bar will be removed automatically.
paginate: 5
paginate_path: "/blog/:num"

# set to value to true to show excerpts of blog on the posts
# and category pages
show_excerpts: false

# Wren-specific settings
wren:
  # Uses `strftime` datetime string formatting.
  date_format: "%Y-%m-%d"  # ISO 8601

  # Generate social links in footer
  social_links:
    # devto: jekyll
    # dribbble: jekyll
    facebook: jekyll  # single user link
    # flickr: jekyll
    github: [jekyll, j3ky11]  # multi user link
    gitlab:  # multi instance link with default instance
    - username: jekyll
    - username: j3ky11
      instance: git.gnome.org
    instagram: jekyll
    # keybase: jekyll
    # linkedin: jekyll
    # mastodon:  # multi-instance link w/o default instance
    # - username: jekyll
    #   instance: mastodon.cloud
    # - username: jekyll2
    #   instance: mastodon.social
    # microdotblog: jekyll
    # pinterest: jekyll
    twitter: jekyllrb
    # youtube: jekyll
    youtube_channel:  # link which makes user of ID
    - username: CloudCannon
      id: UC8CXR0-3I70i1tfPg1PAE1g
    telegram: jekyll

    google-plus: # link not covered by Wren's data
    - username: jekyll
      name: Google+
      instance: plus.google.com/u

  # The header will always include `Home` as the first links and
  # `RSS` and `Top` as the last two links. The ordered list below
  # specifies the other pages to appear in the middle.
  header_pages:
  - blog/index.html
  - about.md

  # The reading speed in 'words per minute' to use when calculating
  # the time taken to read some given content.
  wpm: 180

  # The font size of each category in the category-list.html include
  # is calculated using (a*x + b)%, where x is the category size.
  category_cloud:
    a: 15
    b: 80

# From Jekyll 4.0 theme-gems can no longer include _data so this is
# a workaround to ensure that the data is still provided through a
# config merge.
wren_social_data:
  devto:
    name: DEV
    url:  dev.to
  dribbble:
    name: Dribbble
    url:  dribbble.com
  facebook:
    name: Facebook
    url:  facebook.com
  flickr:
    name: Flickr
    url:  flickr.com/photos
  github:
    name: GitHub
    url:  github.com
  gitlab:
    name: GitLab
    url:  gitlab.com
  instagram:
    name: Instagram
    url:  instagram.com
  keybase:
    name: Keybase
    url:  keybase.io
  linkedin:
    name: LinkedIn
    url:  linkedin.com/in
  mastodon:
    name: Mastodon
  microdotblog:
    name: Micro.blog
    url:  micro.blog
  pinterest:
    name: Pinterest
    url:  pinterest.com
  stackoverflow:
    name: StackOverflow
    url:  stackoverflow.com/users
  telegram:
    name: Telegram
    url:  t.me
  twitter:
    name: Twitter
    url:  twitter.com
  youtube:
    name: YouTube
    url:  youtube.com
  youtube_channel:
    name: YouTube
    url:  youtube.com/channel
