#!/bin/bash

# This is the installer for Wren, a super simple, open source blogging
# platform written in bash. In leau of a package manager this installer
# script will check dependencies are installed and then install Wren.

# Copyright (C) 2014
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License (version 3+) as
# published by the Free Software Foundation. You should have received
# a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.

version="0.2-alpha"

function gerror() {
    echo -e "$1"
    sleep 3
    exit 1
}


echo -e \
    "The following command line installation methods are available.\n" \
    "\r  1.  As a stand-alone website\n" \
    "\r  2.  Alongside an existing website\n" \
    "\r  3.  Using GitHub pages and git\n" \
while true; do
    read -p "\nWhich installation method do you want to use? " answer
    case $answer in
        [1]* ) mode="alone"; break;;
        [2]* ) mode="along"; break;;
        [3]* ) mode="ghgit"; break;;
        * ) echo "Please choose an option from above (1-3)";;
    esac
done


depends=(wget tar date wc)
for package in "${depends[@]}"; do
    if ! type "$package" >> "/dev/null 2>&1"; then
        echo "Using wren requires '$package' to be installed."
        gerror "Please install it and then re-run this script"
    fi
done


# Hosted with GitHub pages
if [ "$mode" == "ghgit" ]; then
    if ! type "git" >> "/dev/null 2>&1"; then
        echo -e \
            "This method requires 'git' to be installed. If\n" \
            "\ryou with to use GitHub pages without git please\n" \
            "\ruse the web-only option. Otherwise, install it\n" \
            "\rand rereun this script to continue."
        gerror
    fi
    
    read -p "What is your GitHub username? " ghuser
    rootdir="$ghuser.github.io"

    git clone "https://github.com/$ghuser/$rootdir.git" || error="True"
    if [ "$error" == True ]; then
        gerror "An error occured! Check above for more info"
    fi
# Hosted via own webserver
elif [ "$mode" == "alone" ] || [ "$mode" == "along" ]; then
    echo -e \
        "Please enter the root location for your website\n" \
        "\rdirectory (can either be absolute or relative).\n" \
        "\rThe path default is taken as '/var/www/html/'."
    
    read -p "Root directory? " rootdir
    if [ -z "$rootdir" ]; then
        rootdir="/var/www/html/"
    fi
    
    if [ -w "$rootdir" ]; then
        echo "Directory accepted"
    else
        mkdir "$rootdir" || error="True"
        if [ "$error" == True ]; then
            echo -e \
                "There was an error while assigning your root\n" \
                "\rlocation. This is most likely because you do\n" \
                "\rnot have write permissions for the directory\n" \
                "\ryou entered. Try running this script as root\n" \
                "\ror use a directory you have prermission for." \
            gerror
        fi
    fi
fi


cd "$rootdir"
# Checks if Wren needs downloading
if ! [ -d .wren ]; then 
    wget "https://github.com/wren-blog/wren/archive/v$version.tar.gz"
    tar xf "v$version.tar.gz"
    mv "wren-$version/*" .
    rm -r "wren-$version" "v$version.tar.gz"
fi


function substitute() {
    # Recursively finds and replaces in current directory
    find . -name "*" -print0 | xargs -0 sed -i '' -e 's/$1/$2/g'
}


echo -e \
    "You will now be asked a series of questions\n" \
    "\rin order to fill in some basic information\n" \
    "\rabout your blog. As of present this can't\n" \
    "\rbe changed by Wren after entering so take\n" \
    "\rcare when inputting your answers!"

read -p "What is your full name? " ans
substitute "USERS_NAME_GOES_HERE" "$ans"

if [ "$mode" == "ghgit" ]; then
    ans="http://$rootdir"
else
    read -p "What is your blog full blog URL? " ans
fi
substitute "URL_GOES_HERE" "$ans"
