#!/bin/bash

# Before running this script please consult the Wren
# GitHub wiki https://github.com/Foggalong/wren/wiki

# Copyright (C) 2014
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License (version 3+) as
# published by the Free Software Foundation. You should have received
# a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.

version="0.1"  # version number
mode="alone"   # default

# Deals with the flags
if [ -z $1 ]
then
	: # pass
else
	case $1 in
		-h|--help)
			echo -e "Usage: ./$(basename -- $0) [OPTION]"
			echo -e "A lightweight blogging platform."
			echo -e ""
			echo -e "Currently supported options:"
			echo -e "  -h, --help \t\t Displays this help menu."
			echo -e "  -v, --version \t Displays program version."
			exit 0 ;;
		-v|--version)
			echo "$(basename -- $0) $version\n"
			exit 0 ;;
		*)
			echo -e "$(basename -- $0): invalid option -- '$1'"
			echo -e "Try '$(basename -- $0) --help' for more information."
			exit 0 ;;
	esac
fi

# Wiki disclaimer
echo -e "Before installing please check the GitHub wiki as"
echo -e "it contains a lot more information on the options"
echo -e "given in this setup.\n"


# Installation method
echo -e "The following installation methods are available.\n"
echo -e "    1.  As a stand-alone website"
echo -e "    2.  Alongside an existing website"
echo -e "    3.  Using GitHub pages and git"
echo -e "    4.  Using GitHub pages (web-only)"

while true; do
	read -p "\nWhich installation method do you want to use? " answer
	case $answer in
		[1]* ) mode="alone"; break;;
		[2]* ) mode="along"; break;;
		[3]* ) mode="ghgit"; break;;
		[4]* ) mode="ghweb"; break;;
		* ) echo "Please choose an option from above (1-4)";;
	esac
done;;


# Preinstallation checks
if [ "$mode" == "ghweb" ]
then
	echo -e "This method is designed for web use only and so"
	echo -e "doesn't require any installation. Go to the wiki"
	echo -e "for more information on this method.\n"
	sleep 3 # Enables error timeout when launched via 'Run in Terminal' command.
	exit 1
elif [ "$mode" == "ghgit" ]
	# Verifies if 'git' is installed
	if type "git" >> "/dev/null 2>&1"
	then
		: # pass
	else
		echo -e "$0: This method requires 'git' to be installed\r
			If you wish to use GitHub pages without using git\r
			please use the web-only option. Otherwise, please\r
			install it and rerun this install script."
		exit 1
	fi
fi