#!/bin/bash

# Tgus script will upgrade a Wren installation to the latest version.
# Until it is in late beta this will just be a blank file as changes
# will just be too drastic.

# Copyright (C) 2014
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License (version 3+) as
# published by the Free Software Foundation. You should have received
# a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.