name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >-
          Thanks for submitting an issue! I'll check it at as soon as possible
          and get back to you.
        pr-message: >-
          Thanks for submitting a PR. Please note that the theme in this repo
          is a personal project and I have limited capacity to maintain
          features I won't be using myself. For that reason I may reject pull
          requests if they're implementing features I don't want or that I
          would implement differently. I promise it's nothing personal! Either
          way, I'll check it out as soon as possible and get back to you.
